// Seasonal reading plans (Advent, Holy Week). Structurally identical to the
// plans in scripts/plans-data.ts — the only difference is the season_key
// tag, which lib/seasons.ts uses to compute each plan's real-world date
// window (Holy Week moves with Easter every year, so that window is
// computed, never stored). No guided prayers on these, consistent with the
// other narrative/survey-style plans (Big Story, book studies, M'Cheyne).

export type SeasonalDaySeed = { label: string; book: string; chapter: number; devotional: string; reflection: string };

export type SeasonalPlanSeed = {
  id: string;
  title: string;
  blurb: string;
  seasonKey: "advent" | "holy-week";
  tags: string[];
  sortOrder: number;
  days: SeasonalDaySeed[];
};

export const SEASONAL_PLANS: SeasonalPlanSeed[] = [
  {
    id: "advent",
    title: "Advent: Waiting for the Light",
    blurb: "24 days from Genesis to Bethlehem — the long promise of “God with us,” traced from creation to the manger.",
    seasonKey: "advent",
    tags: ["advent", "christmas"],
    sortOrder: 20,
    days: [
      { label: "Creation", book: "Genesis", chapter: 1, devotional: "Advent begins, fittingly, at the very beginning: a good world, spoken into being by a God who delights in what he’s made. The story that ends with a baby in Bethlehem starts here — with the claim that this world, and you in it, were never an accident.", reflection: "What would it mean to enter this season believing the world — and your place in it — was made on purpose?" },
      { label: "The first promise", book: "Genesis", chapter: 3, devotional: "Right after everything breaks — trust, harmony, the garden itself — comes the first hint of rescue: a promise that one of Eve’s own offspring will crush the serpent’s head. Advent’s whole shape is already here: darkness, and a promise spoken directly into it.", reflection: "Where in your own life do you most need a promise spoken into the dark?" },
      { label: "Abraham called", book: "Genesis", chapter: 12, devotional: "God’s answer to a broken world isn’t a lecture, it’s a call: leave your country, and through you all the families of the earth will be blessed. One ordinary man, asked to trust a promise he’d never see completed.", reflection: "What would it look like for you to trust a promise on someone else’s timeline, not your own?" },
      { label: "Provision on the mountain", book: "Genesis", chapter: 22, devotional: "On a mountain, with the knife raised, God provides — a ram in the thicket, a son spared. Readers have long heard, echoing forward from this mountain, a promise that God himself will provide what sacrifice requires.", reflection: "Where are you waiting for provision right now, without yet seeing it?" },
      { label: "Jacob’s ladder", book: "Genesis", chapter: 28, devotional: "Fleeing his own family, alone in the wilderness, Jacob dreams of a stairway between heaven and earth — and wakes up saying, ‘surely the LORD was in this place, and I did not know it.’ Advent is, in part, a season for noticing that same nearness.", reflection: "Where might God be nearer to your ordinary days than you’ve noticed?" },
      { label: "The burning bush", book: "Exodus", chapter: 3, devotional: "God speaks from a bush that burns without being consumed — presence itself, appearing right in the middle of the wilderness rather than conquering it from a distance. The name God gives, ‘I AM,’ is a promise of presence before it’s a promise of power.", reflection: "What would it change to expect God’s presence in your wilderness this Advent, not just his intervention?" },
      { label: "An unlikely ancestor", book: "Ruth", chapter: 4, devotional: "A Moabite widow, a foreigner with no claim on Israel’s story, becomes — through loyalty, and a stranger’s kindness — the great-grandmother of King David. The family line that leads to Bethlehem was never as tidy as it might look from a distance.", reflection: "Who in your own story might God be quietly writing into something larger than they know?" },
      { label: "An everlasting throne", book: "2 Samuel", chapter: 7, devotional: "God makes David an audacious promise: a house, a throne, a kingdom established forever. Centuries later, an angel would echo this exact language to a young woman in Nazareth.", reflection: "What promise are you holding onto that requires trusting a timeline far longer than your own life?" },
      { label: "Immanuel", book: "Isaiah", chapter: 7, devotional: "To a frightened king, Isaiah gives a sign: a child will be born, and his name will be Immanuel — God with us. The promise arrives, as it so often does, not as an argument but as a name.", reflection: "What would it mean, specifically, for God to be ‘with you’ in whatever you’re facing right now?" },
      { label: "Unto us a child is born", book: "Isaiah", chapter: 9, devotional: "In the middle of real political darkness, Isaiah promises a child who will be called Wonderful Counselor, Mighty God, Prince of Peace. Hope here isn’t denial of the darkness — it’s a light promised into the middle of it.", reflection: "What darkness in your own life or world do you most need this kind of hope spoken into?" },
      { label: "A shoot from the stump", book: "Isaiah", chapter: 11, devotional: "From what looks like a dead stump — a royal line cut down, a kingdom in ruins — a shoot grows. Advent trusts that God specializes in exactly this: new life from what looks finished.", reflection: "Is there something in your life that feels like a stump, cut down and finished? What would new growth there even look like?" },
      { label: "Comfort, prepare the way", book: "Isaiah", chapter: 40, devotional: "After chapters of judgment, Isaiah’s tone changes completely: ‘comfort, comfort my people,’ says your God. A voice cries out to prepare the way in the wilderness — language John the Baptist would take as his own calling, centuries later.", reflection: "What would it look like for you to actually receive comfort this Advent, rather than just needing it?" },
      { label: "The suffering servant", book: "Isaiah", chapter: 53, devotional: "Long before Bethlehem, Isaiah describes a servant despised and rejected, who carries others’ sorrows as his own. Christmas and Good Friday aren’t as far apart as the calendar makes them look — the child in the manger and the man on the cross are the same story.", reflection: "What does it mean to you that this promised child’s story includes suffering from the very beginning?" },
      { label: "Bethlehem", book: "Micah", chapter: 5, devotional: "Micah names the town almost as an aside — Bethlehem, too small to matter, and yet exactly where the ruler of Israel will come from. God’s pattern, again: the overlooked place, the unlikely person, the quiet beginning.", reflection: "Where in your own life have you assumed you’re too small or too overlooked to matter?" },
      { label: "A new covenant", book: "Jeremiah", chapter: 31, devotional: "After national catastrophe, Jeremiah promises something new: a covenant written not on stone but on the heart, where knowing God is no longer secondhand. Advent looks forward to exactly this kind of nearness, made flesh.", reflection: "What would it mean for faith to be written on your heart, not just something you know about?" },
      { label: "The messenger", book: "Malachi", chapter: 3, devotional: "The Old Testament’s last book closes with a promise of a messenger who will prepare the way — and then centuries of prophetic silence, waiting for that messenger to arrive.", reflection: "What’s it like for you to wait through silence, not knowing when or how an answer will come?" },
      { label: "Two impossible pregnancies", book: "Luke", chapter: 1, devotional: "An old, childless priest and a young, unmarried woman are each given an impossible promise by the same angel. Elizabeth and Mary’s meeting — one leaping for joy before her child is even born — is one of Scripture’s warmest scenes of shared hope.", reflection: "Who in your life shares your hope in a way that makes it feel more real?" },
      { label: "Joseph’s decision", book: "Matthew", chapter: 1, devotional: "Joseph, quietly planning to do the kind thing rather than the harsh one, is given his own angelic visit and his own impossible thing to believe. His genealogy, just before, is full of complicated, even scandalous names — this story was never going to arrive through anyone tidy.", reflection: "What would it take for you to trust something you can’t yet explain to anyone else?" },
      { label: "Born in Bethlehem", book: "Luke", chapter: 2, devotional: "No palace, no announcement to the powerful — the birth Christians celebrate every December happened in an overflow room, first told to shepherds working the night shift. Luke seems to want readers to notice exactly who gets the news first.", reflection: "Who in your own life or world tends to get overlooked, and what would it mean that God shows up for them first?" },
      { label: "The wise men and the star", book: "Matthew", chapter: 2, devotional: "Outsiders from a foreign country follow a star for who knows how long, to kneel before a child they have no cultural claim on. From the very beginning, this story refuses to stay inside the lines anyone expected.", reflection: "Is there a way this season is inviting you further than you expected to go?" },
      { label: "The Word became flesh", book: "John", chapter: 1, devotional: "John doesn’t start with a manger — he starts with eternity: in the beginning was the Word. The claim is staggering: the same voice that spoke creation into being in Genesis 1 became a person you could sit across a table from.", reflection: "What’s one thing you’d want to ask, if it turned out this claim were true?" },
      { label: "God sent his Son", book: "Galatians", chapter: 4, devotional: "Paul compresses the whole Christmas story into a single, dense sentence: when the time had fully come, God sent his Son, born of a woman. Not rushed, not improvised — a promise arriving exactly on time, however long the wait felt to everyone living through it.", reflection: "Where in your life are you waiting for something to arrive ‘in the fullness of time’ rather than on your own schedule?" },
      { label: "He emptied himself", book: "Philippians", chapter: 2, devotional: "Paul quotes what may be the earliest Christian hymn: though he was in very nature God, he emptied himself, taking the nature of a servant. Humility here isn’t a virtue Jesus teaches — it’s the very shape his coming took.", reflection: "Where is humility being asked of you this season?" },
      { label: "God with us, forever", book: "Revelation", chapter: 21, devotional: "The story that began with a promise of ‘God with us’ ends, in Scripture’s final vision, with exactly that: God himself dwelling with humanity, wiping away every tear. Christmas Eve is a good night to remember that the manger was only the beginning of that promise, not the whole of it.", reflection: "What would it mean to you for ‘God with us’ to be not just a Christmas Eve feeling, but a forever one?" },
    ],
  },
  {
    id: "holy-week",
    title: "Holy Week",
    blurb: "Palm Sunday to Easter — eight days walking through the last week of Jesus’s life, one chapter at a time.",
    seasonKey: "holy-week",
    tags: ["holy week", "easter"],
    sortOrder: 21,
    days: [
      { label: "The triumphal entry", book: "Matthew", chapter: 21, devotional: "Jesus enters Jerusalem the way a king would — except riding a borrowed donkey, not a warhorse, fulfilling an old prophecy about a king who comes in humility. The same crowd shouting ‘Hosanna’ today will, within days, be shouting something very different.", reflection: "How quickly do your own convictions about God shift when things don’t go the way you expected?" },
      { label: "Clearing the temple", book: "Mark", chapter: 11, devotional: "Jesus overturns the money-changers’ tables, quoting Isaiah: ‘my house will be called a house of prayer for all nations.’ It’s one of the few times we see him visibly angry — in defense of the outsider’s access to God, not his own honor.", reflection: "Is there something in your own life or community that’s quietly stopped serving the purpose it was meant for?" },
      { label: "Tested in the temple", book: "Matthew", chapter: 22, devotional: "In his last days of public teaching, Jesus is tested again and again — about taxes, resurrection, the greatest commandment — and each time turns the trap into an invitation. ‘Love the Lord your God… and love your neighbor as yourself’ becomes his summary of everything the law and prophets were pointing toward.", reflection: "If someone asked you to summarize your own faith in one sentence, what would you say?" },
      { label: "The anointing at Bethany", book: "John", chapter: 12, devotional: "Six days before Passover, a woman pours expensive perfume over Jesus’s feet — an act some at the table call wasteful, and Jesus calls beautiful. Meanwhile, in the background, the religious leaders are already finalizing a plan to have him killed.", reflection: "What’s something extravagant love has moved you to do, that looked wasteful to someone watching?" },
      { label: "The last supper", book: "Luke", chapter: 22, devotional: "At what he knows is his last meal with his closest friends, Jesus takes bread and wine and reframes them as his own body and blood, given away. Hours later, in a garden, he asks that this cup be taken from him — and then chooses it anyway.", reflection: "Is there a ‘cup’ in your own life you’re being asked to accept, even while wishing it were different?" },
      { label: "The cross", book: "Luke", chapter: 23, devotional: "Luke doesn’t soften the crucifixion — the mockery, the physical agony, the darkness at midday. And in the middle of it, Jesus forgives the men executing him and promises paradise to a criminal dying next to him.", reflection: "Sit with the fact that forgiveness, in this story, comes before anyone asks for it." },
      { label: "The waiting", book: "Matthew", chapter: 27, devotional: "Holy Saturday has no miracle in it — just a sealed tomb, a guard posted, and grief with nowhere yet to go. It’s the one day of the church year built entirely around waiting in the dark, without yet knowing how the story ends.", reflection: "What does it look like for you to sit in an unresolved place, without rushing to fix or explain it?" },
      { label: "Resurrection", book: "Luke", chapter: 24, devotional: "The women who go to anoint Jesus’s body find an empty tomb instead, and are asked a question that echoes through the rest of the book: ‘why do you look for the living among the dead?’ Whatever else Easter means, it means the story didn’t end where everyone assumed it would.", reflection: "What in your own life have you assumed was final that might not be?" },
    ],
  },
];
